#page title
page_title                                : Digits for Vendors                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6745529839                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ZA                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.digits.vendors                                          # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
website_link                              : https://app.vendors.digits.mobi
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Digits for Vendors                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Bitcoin for everyone, everywhere                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Become a Bitcoin voucher vendor in your community. Generate and sell Bitcoin vouchers, earn commission, and process withdrawals easily and securely.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

canonical_url                             : https://vendors.digits.mobi
og_image                                  : # https://vendors.digits.mobi/assets/social-media-banner.png



# Information About Yourself
your_name                                 : Port 8333                               
your_link                                 : https://machankura.com                   
your_city                                 :                                 
email_address                             : developers@machankura.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : Machankura8333
github_username                           : machankura
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Sell Bitcoin Vouchers
    description                           : Become the main vendor of Bitcoin vouchers in your community by enabling people to buy from you.
    fontawesome_icon_name                 : store
    
  - title                                 : Earn commission
    description                           : Generate a voucher for Bitcoin, earn commission on each voucher you sell.
    fontawesome_icon_name                 : coins

  - title                                 : Withdrawals
    description                           : Withdraw commission to your bank account.
    fontawesome_icon_name                 : university

  - title                                 : Accept lightning payments
    description                           : Accept payments for other services.
    fontawesome_icon_name                 : qrcode
# 
  - title                                 : # Smart App Banner
    description                           : # Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : # arrow-alt-circle-down
# 
  - title                                 : # Social Links
    description                           : # Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # link
# 
  - title                                 : # FontAwesome Support
    description                           : # Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.3
topbar_title_color                        : "#ffffff"

cover_image                               : # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#000000"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#F7931A"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#000000"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#000000"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#F7931A"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
